defmodule Cranium.Effects.HandoffWriter do
  @moduledoc """
  Generates handoff documents on session clear.

  A handoff is a summary of the current session, generated by a separate
  LLM call. It captures:
  - What was being worked on
  - Key decisions made
  - Open threads / incomplete work
  - Any context the next session should know

  The handoff is stored via Store and injected into the next session's
  system prompt by PromptBuilder.

  ## Generation

  The handoff prompt asks the model to summarize the conversation without
  tools, in a concise format. This is a separate inference call that
  doesn't affect the main session's context window.
  """

  require Logger

  @handoff_prompt """
  Summarize this conversation for the next session. Include:
  - What was being worked on
  - Key decisions made
  - Open threads or incomplete work
  - Any context the next session should have

  Be concise (under 500 words). Write in past tense. Use markdown.
  """

  @spec generate(String.t()) :: :ok | {:error, term()}
  def generate(room_id) do
    Logger.info("Generating handoff", room_id: room_id, stage: :effects)

    backend = Application.get_env(:cranium, :backends)[:llm]

    {:ok, history} = Cranium.Store.get_messages(room_id, limit: 100)

    messages =
      Enum.map(history, fn msg ->
        %{"role" => to_string(msg[:role] || "user"), "content" => msg[:content] || ""}
      end)

    messages = messages ++ [%{"role" => "user", "content" => @handoff_prompt}]

    case backend.stream_chat(messages, system: "", tools: []) do
      {:ok, stream_pid} ->
        case collect_text(stream_pid) do
          {:ok, text} ->
            Cranium.Store.save_handoff(room_id, text)

          {:error, reason} ->
            Logger.error("Handoff generation failed: #{inspect(reason)}", room_id: room_id)
            {:error, reason}
        end

      {:error, reason} ->
        Logger.error("Handoff LLM call failed: #{inspect(reason)}", room_id: room_id)
        {:error, reason}
    end
  end

  defp collect_text(stream_pid) do
    ref = Process.monitor(stream_pid)
    do_collect(ref, "")
  end

  defp do_collect(ref, acc) do
    receive do
      {:llm_text, text} ->
        do_collect(ref, acc <> text)

      {:llm_stop, _} ->
        Process.demonitor(ref, [:flush])
        {:ok, acc}

      {:DOWN, ^ref, :process, _, reason} ->
        {:error, {:stream_died, reason}}
    after
      60_000 ->
        Process.demonitor(ref, [:flush])
        {:error, :timeout}
    end
  end
end
