defmodule Cranium.Effects.HandoffWriter do
  @moduledoc """
  Generates handoff documents on epoch clear.

  A handoff is a summary of the current epoch, generated by a separate
  LLM call. It captures:
  - What was being worked on
  - Key decisions made
  - Open threads / incomplete work
  - Any context the next epoch should know

  The handoff is stored via Store and injected as a turn-level
  `<room-handoff>` block by TurnInjector on the first turn of the
  next epoch.

  ## Generation

  The handoff prompt is loaded from an external file (Flatnotes) so it
  can be iterated on without code changes. A minimal fallback is used
  if the file is missing. This is a separate inference call that doesn't
  affect the main epoch's context window.
  """

  require Logger

  @handoff_prompt_path "/home/dev/Projects/exocortex/notes/Handoff Instructions.md"

  @spec generate(String.t(), String.t()) :: :ok | {:error, term()}
  def generate(conversation_id, epoch_id) do
    Logger.info("Generating handoff", conversation_id: conversation_id, stage: :effects)

    prompt = load_prompt()
    backend = Application.get_env(:cranium, :backends)[:llm]

    {:ok, history} = Cranium.Store.get_messages(conversation_id, limit: 100, epoch_id: epoch_id)

    messages =
      Enum.map(history, fn msg ->
        %{"role" => to_string(msg[:role] || "user"), "content" => msg[:content] || ""}
      end)

    messages = messages ++ [%{"role" => "user", "content" => prompt}]

    case backend.stream_chat(messages, system: "", tools: []) do
      {:ok, stream_pid} ->
        case collect_text(stream_pid) do
          {:ok, text} ->
            Cranium.Store.save_handoff(conversation_id, text)

          {:error, reason} ->
            Logger.error("Handoff generation failed: #{inspect(reason)}",
              conversation_id: conversation_id
            )

            {:error, reason}
        end

      {:error, reason} ->
        Logger.error("Handoff LLM call failed: #{inspect(reason)}",
          conversation_id: conversation_id
        )

        {:error, reason}
    end
  end

  defp load_prompt do
    case File.read(@handoff_prompt_path) do
      {:ok, content} ->
        String.trim(content)

      {:error, reason} ->
        Logger.warning("Failed to load handoff prompt, using fallback",
          path: @handoff_prompt_path,
          reason: reason
        )

        "Summarize this conversation for the next epoch. Be concise (under 500 words). Write in past tense. Use markdown."
    end
  end

  defp collect_text(stream_pid) do
    ref = Process.monitor(stream_pid)
    do_collect(ref, "")
  end

  defp do_collect(ref, acc) do
    receive do
      {:llm_text, text} ->
        do_collect(ref, acc <> text)

      {:llm_stop, _} ->
        Process.demonitor(ref, [:flush])
        {:ok, acc}

      {:DOWN, ^ref, :process, _, reason} ->
        {:error, {:stream_died, reason}}
    after
      60_000 ->
        Process.demonitor(ref, [:flush])
        {:error, :timeout}
    end
  end
end
