defmodule Cranium.Context.Landscape do
  @moduledoc """
  Reads, merges, and formats the cross-conversation landscape.

  The landscape gives a session awareness of what's happening in other rooms.
  Sources are merged from two places during the v1→v2 transition:

  - **DB summaries** — generated by `ConversationSummarizer` in cranium-v2
  - **Hoard disk** — JSON files written by Go cranium at a configured path

  When both sources have an entry for the same conversation, the more recent
  one wins. The current conversation is always excluded.
  """

  require Logger

  @type entry :: %{
          conversation_id: String.t(),
          room_name: String.t(),
          summary: String.t(),
          last_message_ts: DateTime.t()
        }

  @doc """
  Build the formatted landscape block.

  Returns a `<cross-room-context>` string, or `nil` if there's nothing to show.

  ## Options

  - `:since` — only include entries with `last_message_ts` after this DateTime.
    When `nil`, includes everything (used for turn-1 injection).
  - `:now` — reference time for relative timestamps. Defaults to `DateTime.utc_now()`.
  """
  @spec build(String.t(), keyword()) :: String.t() | nil
  def build(current_conversation_id, opts \\ []) do
    since = Keyword.get(opts, :since)
    now = Keyword.get(opts, :now, DateTime.utc_now())

    entries =
      merge_sources()
      |> Enum.reject(fn e -> e.conversation_id == current_conversation_id end)
      |> filter_since(since)
      |> Enum.sort_by(& &1.last_message_ts, {:desc, DateTime})

    case entries do
      [] -> nil
      items -> format(items, now)
    end
  end

  @doc """
  Load and merge entries from all sources. Exposed for testing.
  """
  @spec merge_sources() :: [entry()]
  def merge_sources do
    db = load_db()
    disk = load_hoard()

    # Merge by conversation_id — prefer the more recent entry
    Map.merge(
      Map.new(db, &{&1.conversation_id, &1}),
      Map.new(disk, &{&1.conversation_id, &1}),
      fn _key, db_entry, disk_entry ->
        if DateTime.compare(db_entry.last_message_ts, disk_entry.last_message_ts) == :gt do
          db_entry
        else
          disk_entry
        end
      end
    )
    |> Map.values()
  end

  # --- Sources ---

  defp load_db do
    try do
      case Cranium.Store.get_all_summaries() do
        {:ok, summaries} ->
          Enum.map(summaries, fn s ->
            %{
              conversation_id: s.conversation_id,
              room_name: s.conversation_id,
              summary: s.content,
              last_message_ts: s.updated_at
            }
          end)

        _ ->
          []
      end
    catch
      :exit, _ -> []
    end
  end

  defp load_hoard do
    path = Application.get_env(:cranium, :paths)[:summaries]

    if path && File.dir?(path) do
      path
      |> File.ls!()
      |> Enum.filter(&String.ends_with?(&1, ".json"))
      |> Enum.flat_map(fn filename ->
        case parse_hoard_file(Path.join(path, filename)) do
          {:ok, entry} -> [entry]
          :error -> []
        end
      end)
    else
      []
    end
  end

  defp parse_hoard_file(filepath) do
    with {:ok, raw} <- File.read(filepath),
         {:ok, json} <- Jason.decode(raw),
         %{"room_name" => room_name, "summary" => summary, "last_message_ts" => ts}
         when is_binary(summary) and summary != "" <- json do
      conversation_id = filepath |> Path.basename(".json")

      {:ok,
       %{
         conversation_id: conversation_id,
         room_name: room_name,
         summary: summary,
         last_message_ts: DateTime.from_unix!(ts)
       }}
    else
      _ -> :error
    end
  end

  # --- Filtering ---

  defp filter_since(entries, nil), do: entries

  defp filter_since(entries, since) do
    Enum.filter(entries, fn e ->
      DateTime.compare(e.last_message_ts, since) == :gt
    end)
  end

  # --- Formatting ---

  defp format(entries, now) do
    lines =
      Enum.map(entries, fn e ->
        ago = humanize_ago(now, e.last_message_ts)
        "- **#{e.room_name}** (last active #{ago}): #{e.summary}"
      end)

    "<cross-room-context>\nHere's what's happening in your other rooms:\n\n" <>
      Enum.join(lines, "\n") <>
      "\n</cross-room-context>"
  end

  defp humanize_ago(now, ts) do
    diff = DateTime.diff(now, ts, :second)

    cond do
      diff < 60 -> "just now"
      diff < 3600 -> "#{div(diff, 60)}m ago"
      diff < 86400 -> "#{div(diff, 3600)}h#{rem(div(diff, 60), 60) |> pad()}m ago"
      true -> "about #{div(diff, 86400)} #{if div(diff, 86400) == 1, do: "day", else: "days"} ago"
    end
  end

  defp pad(n) when n < 10, do: "0#{n}"
  defp pad(n), do: "#{n}"
end
