defmodule Cranium.Inference.Landscape do
  @moduledoc """
  Cross-conversation landscape provider.

  A GenServer that holds the merged summary map in process state, serving
  landscape builds from cache rather than re-reading the DB on every pass.

  Sources are merged from two places:

  - **DB summaries** — generated by `ConversationSummarizer` in cranium
  - **Hoard disk** — legacy JSON files at a configured path (fallback)

  DB entries always take precedence. Hoard entries are loaded once on init
  as a fallback for conversations without a DB summary.

  ## Cache Invalidation

  The ConversationSummarizer sends `{:summary_updated, conversation_id,
  content, updated_at}` after writing a new summary. The GenServer updates
  its entry map in place — no DB re-read required.
  """

  use GenServer

  require Logger

  @type entry :: %{
          conversation_id: String.t(),
          room_name: String.t(),
          summary: String.t(),
          last_message_ts: DateTime.t()
        }

  use TypedStruct

  typedstruct do
    field :entries, %{String.t() => entry()}, default: %{}
  end

  # --- Public API ---

  @spec start_link(keyword()) :: GenServer.on_start()
  def start_link(opts \\ []) do
    name = Keyword.get(opts, :name, __MODULE__)
    GenServer.start_link(__MODULE__, opts, name: name)
  end

  @doc """
  Build the formatted landscape block.

  Returns a `<cross-room-context>` string, or `nil` if there's nothing to show.

  ## Options

  - `:since` — only include entries with `last_message_ts` after this DateTime.
    When `nil`, includes everything (used for turn-1 injection).
  - `:now` — reference time for relative timestamps. Defaults to `DateTime.utc_now()`.
  - `:name` — GenServer name (default `__MODULE__`, used by tests).
  """
  @spec build(String.t(), keyword()) :: String.t() | nil
  def build(current_conversation_id, opts \\ []) do
    name = Keyword.get(opts, :name, __MODULE__)
    since = Keyword.get(opts, :since)
    now = Keyword.get(opts, :now, DateTime.utc_now())

    GenServer.call(name, {:build, current_conversation_id, since, now})
  end

  @doc """
  Notify the Landscape that a summary was updated.

  Called by ConversationSummarizer after writing a summary to Store.
  """
  @spec summary_updated(String.t(), String.t(), DateTime.t()) :: :ok
  def summary_updated(conversation_id, content, updated_at \\ DateTime.utc_now()) do
    GenServer.cast(__MODULE__, {:summary_updated, conversation_id, content, updated_at})
  end

  # --- GenServer Implementation ---

  @impl true
  def init(opts) do
    Logger.info("Landscape provider started", stage: :landscape)

    # Defer loading to handle_continue so the supervisor isn't blocked on DB/disk I/O
    {:ok, %__MODULE__{}, {:continue, {:load, opts}}}
  end

  @impl true
  def handle_continue({:load, _opts}, state) do
    entries = load_and_merge()
    Logger.info("Landscape loaded #{map_size(entries)} entries", stage: :landscape)
    {:noreply, %{state | entries: entries}}
  end

  @impl true
  def handle_call({:build, current_conversation_id, since, now}, _from, state) do
    result =
      state.entries
      |> Map.values()
      |> Enum.reject(fn e -> e.conversation_id == current_conversation_id end)
      |> filter_since(since)
      |> Enum.sort_by(& &1.last_message_ts, {:desc, DateTime})
      |> case do
        [] -> nil
        items -> format(items, now)
      end

    {:reply, result, state}
  end

  @impl true
  def handle_cast({:summary_updated, conversation_id, content, updated_at}, state) do
    entry = %{
      conversation_id: conversation_id,
      room_name: conversation_id,
      summary: content,
      last_message_ts: updated_at
    }

    entries = Map.put(state.entries, conversation_id, entry)
    {:noreply, %{state | entries: entries}}
  end

  # --- Loading ---

  defp load_and_merge do
    db_entries = load_db()
    hoard_entries = load_hoard()

    db_map = Map.new(db_entries, &{&1.conversation_id, &1})
    hoard_map = Map.new(hoard_entries, &{&1.conversation_id, &1})

    # DB entries always win; hoard fills gaps
    Map.merge(hoard_map, db_map)
  end

  defp load_db do
    try do
      case Cranium.Store.get_all_summaries() do
        {:ok, summaries} ->
          Enum.map(summaries, fn s ->
            %{
              conversation_id: s.conversation_id,
              room_name: s.conversation_id,
              summary: s.content,
              last_message_ts: s.updated_at
            }
          end)

        _ ->
          []
      end
    catch
      :exit, _ -> []
    end
  end

  defp load_hoard do
    path = Application.get_env(:cranium, :paths)[:summaries]

    if path && File.dir?(path) do
      path
      |> File.ls!()
      |> Enum.filter(&String.ends_with?(&1, ".json"))
      |> Enum.flat_map(fn filename ->
        case parse_hoard_file(Path.join(path, filename)) do
          {:ok, entry} -> [entry]
          :error -> []
        end
      end)
    else
      []
    end
  end

  defp parse_hoard_file(filepath) do
    with {:ok, raw} <- File.read(filepath),
         {:ok, json} <- Jason.decode(raw),
         %{"room_name" => room_name, "summary" => summary, "last_message_ts" => ts}
         when is_binary(summary) and summary != "" <- json do
      conversation_id = filepath |> Path.basename(".json")

      {:ok,
       %{
         conversation_id: conversation_id,
         room_name: room_name,
         summary: summary,
         last_message_ts: DateTime.from_unix!(ts)
       }}
    else
      _ -> :error
    end
  end

  # --- Filtering ---

  defp filter_since(entries, nil), do: entries

  defp filter_since(entries, since) do
    Enum.filter(entries, fn e ->
      DateTime.compare(e.last_message_ts, since) == :gt
    end)
  end

  # --- Formatting ---

  defp format(entries, now) do
    lines =
      Enum.map(entries, fn e ->
        ago = humanize_ago(now, e.last_message_ts)
        "- **#{e.room_name}** (last active #{ago}): #{e.summary}"
      end)

    "<cross-room-context>\nHere's what's happening in your other rooms:\n\n" <>
      Enum.join(lines, "\n") <>
      "\n</cross-room-context>"
  end

  defp humanize_ago(now, ts) do
    diff = DateTime.diff(now, ts, :second)

    cond do
      diff < 60 -> "just now"
      diff < 3600 -> "#{div(diff, 60)}m ago"
      diff < 86400 -> "#{div(diff, 3600)}h#{rem(div(diff, 60), 60) |> pad()}m ago"
      true -> "about #{div(diff, 86400)} #{if div(diff, 86400) == 1, do: "day", else: "days"} ago"
    end
  end

  defp pad(n) when n < 10, do: "0#{n}"
  defp pad(n), do: "#{n}"
end
